---
title: "Data Preprocessing"
output: html_notebook
author: Jeff Gross
---

Install packages

```{r}
install.packages("caTools")
```

Importing the dataset

```{r}
dataset = read.csv('Data.csv')
# dataset = dataset[, 2:3]
```

Taking care of missing data

```{r}
dataset$Age = ifelse(is.na(dataset$Age), #true if any values in the column are missing, false if not missing
                     ave(dataset$Age, FUN = function(x) mean(x, na.rm = TRUE)),
                     dataset$Age)
dataset$Salary = ifelse(is.na(dataset$Salary),
                        ave(dataset$Salary, FUN = function(x) mean(x, na.rm = TRUE)),
                        dataset$Salary)
```

Encoding categorical data

```{r}
dataset$Country = factor(dataset$Country,
                         levels = c('France', 'Spain', 'Germany'), #c creates a vector in R
                         labels = c(1, 2, 3))
dataset$Purchased = factor(dataset$Purchased,
                           levels = c('No', 'Yes'),
                           labels = c(0, 1))
```

Splitting the dataset into the Training set and Test set

```{r}
library(caTools)
set.seed(613)
split = sample.split(dataset$DependentVariable, SplitRatio = 0.8) #% for training set
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)
```

Feature Scaling

```{r}
training_set[,2:3] = scale(training_set[,2:3]) #other columns were factors, not numerical (see Encoding categorical)
test_set[,2:3] = scale(test_set[,2:3]) #other columns were factors, not numerical (see Encoding categorical)
```



